apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policy-tenant
  namespace: {{ .Values.vault.namespace }}
data:
  tenant.hcl: |
    path "secret/data/tenant/{{identity.entity.aliases.auth_kubernetes_cluster_1.metadata.tenantId}}/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/tenant/{{identity.entity.aliases.auth_kubernetes_cluster_1.metadata.tenantId}}/*" {
      capabilities = ["list", "read"]
    }
