apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.eso.vaultAddress | quote }}
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: {{ .Values.eso.caProvider.name }}
        key: {{ .Values.eso.caProvider.key }}
        namespace: {{ .Values.eso.caProvider.namespace }}
      auth:
        kubernetes:
          mountPath: {{ .Values.eso.vaultAuthPath | quote }}
          role: {{ .Values.eso.vaultAuthRole | quote }}
          serviceAccountRef:
            name: {{ .Values.eso.serviceAccountName }}
            namespace: {{ .Values.eso.namespace }}
          tokenExpirationSeconds: 86400
