apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Values.vault.namespace }}
spec:
  type: {{ .Values.vault.service.type }}
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: http
      port: {{ .Values.vault.service.port }}
      targetPort: 8200
    - name: cluster
      port: {{ .Values.vault.service.clusterPort }}
      targetPort: 8201
---
apiVersion: v1
kind: Service
metadata:
  name: vault-internal
  namespace: {{ .Values.vault.namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: cluster
      port: 8201
      targetPort: 8201
