{{- if ne .Values.controlPlaneExecutor.enabled false }}
{{- $verifier := include "in-falcone.issuerJwksAuth" . | fromJson -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-executor-jwt-config
  labels:
    {{- include "in-falcone.labels" . | nindent 4 }}
    in-falcone.io/component: control-plane-executor
data:
  KEYCLOAK_ISSUER: {{ printf "%s/realms/%s" $verifier.issuer_base_url $verifier.platform_realm | quote }}
  KEYCLOAK_JWKS_URL: {{ printf "%s/realms/%s/protocol/openid-connect/certs" $verifier.jwks_base_url $verifier.platform_realm | quote }}
  KEYCLOAK_AUDIENCE: {{ $verifier.audience | quote }}
{{- end }}
