{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "in-falcone.labels" . | nindent 4 }}
    in-falcone.io/environment: {{ .Values.global.environment | quote }}
{{- end }}
