{{- $releaseNamespace := .Release.Namespace -}}
{{- $esoNamespace := .Values.eso.eso.namespace | default "eso-system" -}}
{{- $openbaoNamespace := .Values.openbao.openbao.namespace | default "secret-store" -}}
{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $releaseNamespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "in-falcone.labels" . | nindent 4 }}
    in-falcone.io/environment: {{ .Values.global.environment | quote }}
    kubernetes.io/metadata.name: {{ $releaseNamespace | quote }}
    openbao-access: "true"
{{- if ne $esoNamespace $releaseNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $esoNamespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "in-falcone.labels" . | nindent 4 }}
    in-falcone.io/environment: {{ .Values.global.environment | quote }}
    kubernetes.io/metadata.name: {{ $esoNamespace | quote }}
{{- end }}
{{- if and (ne $openbaoNamespace $releaseNamespace) (ne $openbaoNamespace $esoNamespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $openbaoNamespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "in-falcone.labels" . | nindent 4 }}
    in-falcone.io/environment: {{ .Values.global.environment | quote }}
    kubernetes.io/metadata.name: {{ $openbaoNamespace | quote }}
{{- end }}
{{- end }}
