deployment:
  profile: all-in-one
apisix:
  replicas: 1
keycloak:
  replicas: 1
kafka:
  replicas: 1
  persistence:
    size: 20Gi
openwhisk:
  replicas: 1
controlPlane:
  replicas: 1
webConsole:
  replicas: 1
observability:
  enabled: false
postgresql:
  persistence:
    size: 10Gi
mongodb:
  persistence:
    size: 10Gi
storage:
  persistence:
    size: 20Gi
