apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-policy-gateway
  namespace: {{ .Values.openbao.namespace }}
data:
  gateway.hcl: |
    path "secret/data/gateway/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/gateway/*" {
      capabilities = ["list", "read"]
    }
