apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-policy-platform
  namespace: {{ .Values.openbao.namespace }}
data:
  platform.hcl: |
    path "secret/data/platform/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/platform/*" {
      capabilities = ["list", "read"]
    }
