apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-policy-tenant
  namespace: {{ .Values.openbao.namespace }}
data:
  tenant.hcl: |
    path "secret/data/tenant/{{ "{{" }}identity.entity.aliases.auth_kubernetes_cluster_1.metadata.tenantId{{ "}}" }}/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/tenant/{{ "{{" }}identity.entity.aliases.auth_kubernetes_cluster_1.metadata.tenantId{{ "}}" }}/*" {
      capabilities = ["list", "read"]
    }
