{{- if .Values.openbao.authReconcile.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-auth-reconciler
  namespace: {{ .Values.openbao.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-policy-auth-reconcile
  namespace: {{ .Values.openbao.namespace }}
data:
  auth-reconcile.hcl: |{{ include "openbao.policy.authReconcile" . | nindent 4 }}
{{- end }}
