apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data
  namespace: {{ .Values.openbao.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.openbao.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.openbao.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-audit
  namespace: {{ .Values.openbao.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.openbao.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: 2Gi
