apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao
  namespace: {{ .Values.openbao.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.eso.serviceAccountName | default "eso-openbao-auth" }}
  namespace: eso-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-kubernetes-auth
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "serviceaccounts/token", "nodes"]
    verbs: ["get", "create"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-kubernetes-auth
subjects:
  - kind: ServiceAccount
    name: openbao
    namespace: {{ .Values.openbao.namespace }}
  - kind: ServiceAccount
    name: {{ .Values.eso.serviceAccountName | default "eso-openbao-auth" }}
    namespace: eso-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openbao-kubernetes-auth
