apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iam-keycloak-credentials
  namespace: keycloak
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  refreshInterval: {{ $.Values.eso.refreshInterval | quote }}
  secretStoreRef: { name: openbao-backend, kind: ClusterSecretStore }
  target: { name: iam-keycloak-credentials, immutable: false }
  data:
    - secretKey: admin-password
      remoteRef: { key: iam/keycloak, property: admin-password }
    - secretKey: db-password
      remoteRef: { key: iam/keycloak, property: db-password }
