apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-mongodb-credentials
  namespace: mongodb
spec:
  refreshInterval: {{ $.Values.eso.refreshInterval | quote }}
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target: { name: platform-mongodb-credentials, immutable: true }
  data:
    - secretKey: root-password
      remoteRef: { key: platform/mongodb, property: root-password }
    - secretKey: app-password
      remoteRef: { key: platform/mongodb, property: app-password }
