apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-openwhisk-credentials
  namespace: openwhisk
spec:
  refreshInterval: {{ $.Values.eso.refreshInterval | quote }}
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target: { name: platform-openwhisk-credentials, immutable: false }
  data:
    - secretKey: db-password
      remoteRef: { key: platform/openwhisk, property: db-password }
