apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app.kubernetes.io/name: backup-status
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  DB_URL: {{ .Values.env.DB_URL | quote }}
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | quote }}
  KEYCLOAK_JWKS_URL: {{ .Values.env.KEYCLOAK_JWKS_URL | quote }}
