deployment:
  profile: all-in-one
apisix:
  replicas: 1
keycloak:
  replicas: 1
kafka:
  replicas: 1
  persistence:
    size: 20Gi
controlPlane:
  replicas: 1
webConsole:
  replicas: 1
postgresql:
  persistence:
    size: 10Gi
documentdb:
  persistence:
    size: 10Gi
